# Use an official node image as the base
FROM node:20

# Set working directory to /app
WORKDIR /app

# Copy package*.json files
COPY package.json package-lock.json ./

# Install dependencies

RUN npm install

# Copy the rest of the app
COPY . .

# Build the app
RUN npm run build

# Expose the port
EXPOSE 3000

# Run the command to start the development server
CMD ["npm", "run", "dev"]